version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    env_file: .env
    environment:
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "$MYSQL_PORT:3306"
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    image: wordpress:5-fpm-alpine
    depends_on:
      - db
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/$THEME_NAME
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$DB_NAME
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "$PORT:80"
      - "$SSL_PORT:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbotdata:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbotdata:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email i.dobrovolskiy111@gmail.com --agree-tos --no-eff-email --force-renewal -d tutidobr.tutdomen.com -d www.tutidobr.tutdomen.com

volumes:
  wordpress:
  dbdata:
  nginx:
  certbotdata:

networks:
  app-network:
    driver: bridge
